# tasks file

- name: Backup main redis config file
  command: cp /etc/redis-sentinel.conf /etc/redis-sentinel.conf.default
  ignore_errors: no

- name: copy redis.conf to the aproppriate place
  template: src=redis-sentinel.conf.j2 dest=/etc/redis-sentinel.conf
  notify: restart redis-sentinel

