---
# task for installation zabbix-agent from appropriate repo

- name: Adding appropriate repository to the system
  yum: name=https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm state=present
  ignore_errors: no

- name: Installing zabbix-agent package from the repository
  yum:  name="{{ item }}" state=present
  ignore_errors: no
  with_items:
    - zabbix-agent
    - zabbix-sender
  notify: start zabbix-agent
