---
# handlers file for playbook-redis

- name: start redis
  systemd: name=redis state=started

- name: reload redis
  systemd: name=redis state=reloaded

- name: stop redis
  systemd: name=redis state=stopped

- name: start redis-sentinel
  systemd: name=redis-sentinel state=started

- name: reload redis-sentinel
  systemd: name=redis-sentinel state=reloaded

- name: stop redis-sentinel
  systemd: name=redis-sentinel state=stopped


- name: yum-clean-all
  command: yum clean all
  args:
    warn: no

