# playbook-setup-redis-cluster.yml
---
- hosts: redis-cluster-nodes
  become: yes
  roles:
          - { role: role-redis-base }
          - { role: role-redis-sentinel }

- hosts: redis-master
  become: yes
  roles:
          - { role: role-redis-master }

- hosts: redis-slaves
  become: yes
  roles:
          - { role: role-redis-slaves }

